### ISSUE TITLE
Mewmba link to Slack

### ISSUE THREAD

**Issue by fundthmcalculus** [trinsic-id/mewmba#35]
- [x] Should notify the `#gather` channel whenever someone joins gather
- [x] Should support listening to slack command `/mewmba` to help people out
- [x] Should support links to notion and github `/mewmba ticket this thread`
  - [x] Collect all messages in a thread, reverse the order, strip the date-time information
  - [x] Add link to the message that began the thread.
  - [x] Post a ticket in github or a doc in notion (?where?)
  - [x] ~`/mewmba copy this thread` should do the above, but add it to your clipboard / post-back message only to you to copy?~

**Comment by chiarapaskulin** [comment]
These would be amazinggg to have!! 🤩🔥
